/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    FavoriteModal: typeof import('./src/components/FavoriteModal.vue')['default']
    IconLike: typeof import('./src/components/icons/IconLike.vue')['default']
    IconLogo: typeof import('./src/components/icons/IconLogo.vue')['default']
    NavButton: typeof import('./src/components/Home/NavButton.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./src/components/SearchForm.vue')['default']
    SlidesPerView: typeof import('./src/components/SlidesPerView.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheNav: typeof import('./src/components/TheNav.vue')['default']
    TheSelect: typeof import('./src/components/TheSelect.vue')['default']
    ThumbsGallery: typeof import('./src/components/ThumbsGallery.vue')['default']
  }
}
